# Generated by Django 3.1.7 on 2021-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('org', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('phone', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('detail', models.TextField()),
                ('theme', models.CharField(max_length=250)),
                ('guidelines', models.TextField()),
                ('elig_cri', models.TextField()),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
