# Generated by Django 3.1.7 on 2021-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210318_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
