# Generated by Django 3.1.7 on 2021-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
