# Generated by Django 3.1.7 on 2021-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Contact_no2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Email_address2',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Gender2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='House_Address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Results',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Student_Name_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
