# Generated by Django 3.1.7 on 2021-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210327_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='Last_Submission_Date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Image_of_Project',
            field=models.ImageField(default='', upload_to='core/images'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Link_of_your_project',
            field=models.URLField(),
        ),
    ]
