# Generated by Django 3.1.7 on 2021-03-27 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210327_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Last_Submission_Date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
