# Generated by Django 3.1.7 on 2021-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210327_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Last_Submission_Date',
            field=models.DateField(default=1089),
        ),
    ]
