# Generated by Django 3.1.7 on 2021-03-27 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210327_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Last_Submission_Date',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 9, 59, 6, 581785, tzinfo=utc)),
        ),
    ]
