# Generated by Django 3.1.7 on 2021-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Last_Submission_Date',
            field=models.CharField(max_length=100),
        ),
    ]
