# Generated by Django 3.1.7 on 2021-03-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210327_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='Last_Submission_Date',
        ),
    ]
